### ISSUE TITLE
Updating to v0.6 leads to error

### ISSUE THREAD

**Issue by djmtype** [MWDelaney/sage-acf-wp-blocks#52]
After updating to sage-acf-wp-blocks from v0.5 to v0.6, WordPress throws an error. I haven't changed any of my blocks' syntax or location. 

I also tried removing this block from my directory, but then I got the same error for the next block.

```
Fatal error: Uncaught InvalidArgumentException: View [views.blocks.alert] not found. in /Users/scottrod/Sites/maridose/wp-content/themes/maridose/vendor/illuminate/view/FileViewFinder.php:137 Stack trace: #0 /Users/scottrod/Sites/maridose/wp-content/themes/maridose/vendor/illuminate/view/FileViewFinder.php(79): Illuminate\View\FileViewFinder->findInPaths('views.blocks.al...', Array) #1 /Users/scottrod/Sites/maridose/wp-content/themes/maridose/vendor/illuminate/view/Factory.php(128): Illuminate\View\FileViewFinder->find('views.blocks.al...') #2 [internal function]: Illuminate\View\Factory->make('views.blocks.al...', Array, Array) #3 /Users/scottrod/Sites/maridose/wp-content/themes/maridose/vendor/roots/sage-lib/Template/Blade.php(138): call_user_func_array(Array, Array) #4 /Users/scottrod/Sites/maridose/wp-content/themes/maridose/vendor/roots/sage-lib/Template/Blade.php(58): Roots\Sage\Template\Blade->__call('make', Array) #5 /Users/scottrod/Sites/maridose/wp-content/themes/maridose/app/helpers.php(55): Roots\Sage\Template in /Users/scottrod/Sites/maridose/wp-content/themes/maridose/vendor/illuminate/view/FileViewFinder.php on line 137
```

My block

```php
{{--
  Title: Alert
  Category: formatting
  Icon: megaphone
  PostTypes: page post
  SupportsAlign: false
  SupportsMode: true
  SupportsMultiple: true
  Mode: edit
--}}


@php
$classes = '';
$alert_class = '';
$alert_color = get_field('alert_color');
$alert_content = get_field('alert_content')
@endphp

@if( !empty($block['className']) ) 
    @php $classes .= sprintf( ' %s', $block['className'] ) @endphp
@endif

@if($alert_color == 'primary')
@php $alert_class = 'alert-primary' @endphp
@elseif ($alert_color == 'secondary')
@php $alert_class = 'alert-secondary' @endphp
@elseif ($alert_color == 'default')
@php $alert_class = 'alert-default' @endphp
@endif

<section class="alert {!! $alert_class !!} {!! $classes !!}">

<div class="container max-width-lg flow-xs-y">
		{!! $alert_content !!}
	</div>
	<!-- /.container -->

</section>
```

**Comment by speakerbug** [comment]
Just an FYI this is actually already opened as an issue #50 and there's a fix as a pull request #51 but it's been sitting for almost two weeks now.

**Comment by blift** [comment]
Hi I have aded pull request with fixed error, please verify

**Comment by robmeijerink** [comment]
@MWDelaney Some people are facing issues in Sage 9. Any chance you can merge the PR that fixes this?

**Comment by blift** [comment]
@MWDelaney and @robmeijerink please verify pull request #51 before merge, in my case still it not working on sage 9, I've added #53 pull request with update, but not tested with sage 10. The path result is the same in sage_blocks_callback method line 221, so should work properly.

**Comment by syclone** [comment]
Hi, I just installed this plugin and got the same error with v0.6. I decided to try v0.5 after reading through these issues and it worked fine. For anyone who is like me and looking for a workaround, v0.5 did the trick. 

So just install it like so: 

`composer require mwdelaney/sage-acf-gutenberg-blocks:0.5`

**Comment by tombroucke** [comment]
I have created a pull request that fixes this issue. In the meantime, you can fix the issue  by updating the template() function in helpers.php:
```
function template($file, $data = [])
{
    if( !file_exists( $file ) ) {
         $file = locate_template($file);
    }
    return sage('blade')->render($file, $data);
}
```

**Comment by joshuafredrickson** [comment]
This is fixed in 0.7.
